Update playmusicdecrypter.py
I found in the Windows environment, "os.remove" on line 193 creates the error condition 
'
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\com.google.android.music\\files\\music\\1026.mp3'
'

By removing this line, the script executes perfectly